### ISSUE TITLE
How publishing works?

### ISSUE THREAD

**Issue by Morganov** [progit/progit2-pub#12]
Due to migration from TravisCI to GitHub Actions, the process of publishing new versions to http://git-scm.com/book/ seems to be broken. The reason for that is the usage of customized workflows by each project.

I reviewed the repository with templates (in particular, https://github.com/progit/.github/blob/master/workflow-templates/release-on-merge.yml) and didn't find the action to publish content.

Could you clarify what are the requirements for building artifacts to have them published as a new version is released?

**Comment by jnavila** [comment]
I took a different approach for translations than the one used by github.com. The github workflow in each translation repository is a bootstrap that downloads from this repository and runs the main publishing scripts. So, for instance for progit2-be, you can see here the bootstrap for pull requests: https://github.com/progit/progit2-be/blob/master/.github/workflows/pr-build.yml

Then the build is performed by the github action with the Rakefile and the Gemfile from this repo. the original files in the translation repo are overwrittern. So, if you want to mimic what happens you have to download these files here and copy them into you working copy.

**Comment by jnavila** [comment]
The build of your book is aborted because some checks are failing: https://github.com/progit/progit2-be/runs/6908296075?check_suite_focus=true

**Comment by jnavila** [comment]
Ah, I see. This is not about publishing the books as ebook or PDF, this is about the publishing on git-scm.com.

In this case, you are right. This is a bug at git-scm.com or the update script is no longer working. Please open an issue there.
