### ISSUE TITLE
Add changelog to each release

### ISSUE THREAD

**Issue by jnavila** [progit/progit2-pub#2]
We could automatically build a changelog by collecting the new (non-merge) commits logs and pushing them to the release we are building.

**Comment by networm** [comment]
`git log --format="%s" --no-merges a..b` and travis has the range of the commit.

**Comment by jnavila** [comment]
I'm looking at https://github.com/skywinder/github-changelog-generator/blob/master/README.md

That seems to work with github PRs and integrate better with Rake. What do you think?

**Comment by networm** [comment]
I have browsed it, I think it is very good.

**Comment by networm** [comment]
I have triggered a build but it seems didn't work.
[Release 2.1.7 · progit/progit2-zh](https://github.com/progit/progit2-zh/releases/tag/2.1.7)

**Comment by jnavila** [comment]
No the changelog generation does not work for the moment. I still have to understand how tagging and releasing actually work.

**Comment by networm** [comment]
Oh, I know. Could you notify me if it’s completed?
