### ISSUE TITLE
progit2-zh build failed

### ISSUE THREAD

**Issue by networm** [progit/progit2-pub#5]
Build #130 - progit/progit2-zh - Travis CI
https://travis-ci.org/progit/progit2-zh/builds/644341701

Same build script but succeed in progit2 official repository

Build #830 - progit/progit2 - Travis CI
https://travis-ci.org/progit/progit2/builds/643923526

**Comment by jnavila** [comment]
That's strange because the Gemfile and Rakefile haven't changed for quite a while now. Note that the script for progit2 cannot be used for progit2-zh because of needed CJK typesetting. The extensions asciidoctor-pdf-cjk and asciidoctor-pdf-cjk_kaigen_gothic are used. It may come from changes in style  handling.

**Comment by jnavila** [comment]
OK, so this Gemfile works:

```
source 'https://rubygems.org'

gem 'rake'
gem 'asciidoctor', '1.5.6.2'

gem 'json'
gem 'awesome_print'

gem 'ttfunk', '= 1.5.1'
gem 'asciidoctor-epub3', '1.5.0.alpha.9'
gem 'asciidoctor-pdf', '1.5.0.alpha.16'
gem 'asciidoctor-pdf-cjk', '~> 0.1.3'
gem 'asciidoctor-pdf-cjk-kai_gen_gothic', '~> 0.1.1'

gem 'coderay'
gem 'pygments.rb'
gem 'thread_safe'
gem 'epubcheck-ruby'
gem 'kindlegen'

gem 'octokit'
gem 'github_changelog_generator', github: 'Furtif/github-changelog-generator'
```

It seems that `ttfunk` needs to be pinned and `asciidoctor-pdf` greater than 1.5.0.alpha.16 breaks compatibility with `asciidoctor-pdf-cjk` and `asciidoctor-pdf-cjk-kai_gen_gothic`. It's not clear what lead to this regression, though.

**Comment by networm** [comment]
I have change travis.yml to do not download Gemfile and Rakefile from progit/progit-pub. And I change to use custom Gemfile which you provided and it works. Thank you!

Build #134 - progit/progit2-zh - Travis CI
https://travis-ci.org/progit/progit2-zh/builds/644961117

**Comment by jnavila** [comment]
I'll have a look at what using asciidoctor-pdf-cjk and asciidoctor-pdf-cjk_kaigen_gothic implies w.r.t. updating asciidoctor (that's a project for us). In the mean time, I can apply the changes to the Gemfile, so that we can stay with using the files from progit2-pub
